### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by MAYDAY1993** [hugzh/vue-demo#1]
在  Nav.vue 第19行 
![image](https://cloud.githubusercontent.com/assets/14831051/19340423/65c4e49e-915b-11e6-88da-78a43cc2a26a.png)
应该是{{current}}吧

**Comment by hugzh** [comment]
不是的，这不是一个模板变量。

**Comment by hugzh** [comment]
不是的，这不是模板变量，值是一个字符
